name: magic_fit_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #storage
  hive: ^2.2.3

  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  hive_flutter: ^1.1.0
  dev: ^1.0.0
  
  path_provider: ^2.1.4
  #App Navigation
  go_router: ^14.2.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  #Testing app
  mocktail: ^1.0.4
  mockito: ^5.4.4
  hive_test: ^1.0.1
  bloc_test: ^9.1.7

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  